name: nginx-rtmp
version: "1.0"
summary: NGINX-based Media Streaming Server
description: "For more details please visit our site: https://github.com/daker/nginx-rtmp-snap"

grade: devel
confinement: devmode

apps:
    start:
        plugs: [network-bind]
        command: bin/start.sh

    reload:
        plugs: [network-bind]
        command: bin/reload.sh

    stop:
        plugs: [network-bind]
        command: bin/stop.sh

parts:
    wrappers:
        plugin: dump
        source: ./extras
    nginx:
        plugin: autotools
        source: https://nginx.org/download/nginx-1.13.0.tar.gz
        build-packages:
            - libpcre3-dev
            - libssl-dev
        configflags:
            - --with-http_ssl_module
            - --add-module=../../../nginx-rtmp-module
        organize:
            sbin: bin