name: nginx-rtmp
version: "1.0"
summary: NGINX-based Media Streaming Server
description: "For more details please visit our site: https://github.com/daker/nginx-rtmp-snap"

grade: devel
confinement: devmode

apps:
    nginx-service:
        command: bin/nginx.sh start
        daemon: simple
        plugs: [network-bind]

parts:
    wrappers:
        plugin: dump
        source: ./extras
    nginx:
        plugin: autotools
        source: https://nginx.org/download/nginx-1.13.0.tar.gz
        build-packages:
            - libpcre3-dev
            - libssl-dev
        configflags: [
            "--conf-path=/snap/nginx-rtmp/current/etc/nginx/nginx.conf",
            "--error-log-path=/snap/nginx-rtmp/current/etc/nginx/log/error.log",
            "--http-log-path=/snap/nginx-rtmp/current/etc/nginx/log/access.log",
            "--pid-path=/snap/nginx-rtmp/current/etc/nginx/run/nginx.pid",
            "--with-http_ssl_module",
            "--add-module=../../../nginx-rtmp-module"]
        organize:
            sbin: bin
        prime:
            - -html
            - -var
            - -snap